//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBooking.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotBooking.Resources.Views.Home.Country", typeof(Country).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city trips.
        /// </summary>
        public static string city_trips {
            get {
                return ResourceManager.GetString("city trips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore and find Hotels in.
        /// </summary>
        public static string Explore_and_find_Hotels_in {
            get {
                return ResourceManager.GetString("Explore and find Hotels in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotel.
        /// </summary>
        public static string hotel {
            get {
                return ResourceManager.GetString("hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel in.
        /// </summary>
        public static string Hotel_in {
            get {
                return ResourceManager.GetString("Hotel in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotels.
        /// </summary>
        public static string hotels {
            get {
                return ResourceManager.GetString("hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasant.
        /// </summary>
        public static string Pleasant {
            get {
                return ResourceManager.GetString("Pleasant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviews.
        /// </summary>
        public static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superb.
        /// </summary>
        public static string Superb {
            get {
                return ResourceManager.GetString("Superb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top destinations for.
        /// </summary>
        public static string Top_destinations_for {
            get {
                return ResourceManager.GetString("Top destinations for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top hotels in.
        /// </summary>
        public static string Top_hotels_in {
            get {
                return ResourceManager.GetString("Top hotels in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string Very_Good {
            get {
                return ResourceManager.GetString("Very Good", resourceCulture);
            }
        }
    }
}
