//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBooking.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotBooking.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Dedicated Customer Care Team.
        /// </summary>
        public static string _24_7_Dedicated_Customer_Care_Team {
            get {
                return ResourceManager.GetString("24/7 Dedicated Customer Care Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our customer care team is available 24/7. Our managers can help you with choosing a hotel and making a reservation, or if you need any help when traveling, they will find a solution to your problem as soon as possible..
        /// </summary>
        public static string _24_7_Dedicated_Customer_Care_Team_desc {
            get {
                return ResourceManager.GetString("24/7 Dedicated Customer Care Team desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Armenia.
        /// </summary>
        public static string Explore_Armenia {
            get {
                return ResourceManager.GetString("Explore Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite cities.
        /// </summary>
        public static string Favorite_cities {
            get {
                return ResourceManager.GetString("Favorite cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible payment options.
        /// </summary>
        public static string Flexible_payment_options {
            get {
                return ResourceManager.GetString("Flexible payment options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose a payment method. We accept all major credit cards for online payment. You can also pay upon arrival at the hotel..
        /// </summary>
        public static string Flexible_payment_options_desc {
            get {
                return ResourceManager.GetString("Flexible payment options desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free App.
        /// </summary>
        public static string Free_App {
            get {
                return ResourceManager.GetString("Free App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most important thing about our app is that it shows secret offers. Plus, it is extremely handy—book hotels on the subway, at work, or even at the airport..
        /// </summary>
        public static string Free_App_desc {
            get {
                return ResourceManager.GetString("Free App desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotBooking – Armenian online service for booking accommodations worldwide. You will enjoy our website if you value your time, money and ability of choice. Our search takes few minutes but result will impress each traveler. You can easily find the best room for you through our data and book hotel immediately. Among accommodations offered: hotels, apartments, hostels, guest houses, bungalows in any part of the world. HotBooking doesn’t charge you hidden commissions and fees – book hotel for the best prices wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotBooking_desc {
            get {
                return ResourceManager.GetString("HotBooking desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online hotel reservation system HotBooking.
        /// </summary>
        public static string HotBooking_title {
            get {
                return ResourceManager.GetString("HotBooking title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels Worldwide.
        /// </summary>
        public static string Hotels_Worldwide {
            get {
                return ResourceManager.GetString("Hotels Worldwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have over 1,300,000 properties around the world. This includes hotels, hostels, apartments, villas, and even campgrounds. Find suitable accommodation at any time of the year..
        /// </summary>
        public static string Hotels_Worldwide_desc {
            get {
                return ResourceManager.GetString("Hotels Worldwide desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest reviews.
        /// </summary>
        public static string Latest_reviews {
            get {
                return ResourceManager.GetString("Latest reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Learn_more {
            get {
                return ResourceManager.GetString("Learn more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low prices.
        /// </summary>
        public static string Low_prices {
            get {
                return ResourceManager.GetString("Low prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our prices are under close control as we work with thousands of hotels and dozens of providers directly. This also means that we always have great offers for most destinations..
        /// </summary>
        public static string Low_prices_desc {
            get {
                return ResourceManager.GetString("Low prices desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online hotel reservation system HotBooking.
        /// </summary>
        public static string Online_hotel_reservation_system_HotBooking {
            get {
                return ResourceManager.GetString("Online hotel reservation system HotBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliable Reviews.
        /// </summary>
        public static string Reliable_Reviews {
            get {
                return ResourceManager.GetString("Reliable Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We collect and publish our clients&apos; reviews, as well as reviews from TripAdvisor, to provide you with additional information about the hotel..
        /// </summary>
        public static string Reliable_Reviews_desc {
            get {
                return ResourceManager.GetString("Reliable Reviews desc", resourceCulture);
            }
        }
    }
}
