//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotBooking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotBooking.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HotBooking.com.
        /// </summary>
        public static string About_HotBooking_com {
            get {
                return ResourceManager.GetString("About HotBooking.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date.
        /// </summary>
        public static string Arrival_date {
            get {
                return ResourceManager.GetString("Arrival date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book hotels anywhere in the world.
        /// </summary>
        public static string Book_hotels_anywhere_in_the_world {
            get {
                return ResourceManager.GetString("Book hotels anywhere in the world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers.
        /// </summary>
        public static string Careers {
            get {
                return ResourceManager.GetString("Careers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check prices.
        /// </summary>
        public static string Check_prices {
            get {
                return ResourceManager.GetString("Check prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2020 HotBooking.com All rights reserved..
        /// </summary>
        public static string Copyright_2020_HotBooking_com_All_rights_reserved_ {
            get {
                return ResourceManager.GetString("Copyright 2020 HotBooking.com All rights reserved.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer support.
        /// </summary>
        public static string Customer_support {
            get {
                return ResourceManager.GetString("Customer support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of departure.
        /// </summary>
        public static string Date_of_departure {
            get {
                return ResourceManager.GetString("Date of departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from centre of.
        /// </summary>
        public static string Distance_from_centre_of {
            get {
                return ResourceManager.GetString("Distance from centre of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not sell my personal information.
        /// </summary>
        public static string Do_not_sell_my_personal_information {
            get {
                return ResourceManager.GetString("Do not sell my personal information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by:.
        /// </summary>
        public static string Filter_by_ {
            get {
                return ResourceManager.GetString("Filter by:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel reviews.
        /// </summary>
        public static string Hotel_reviews {
            get {
                return ResourceManager.GetString("Hotel reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels name or city.
        /// </summary>
        public static string Hotels_name_or_city {
            get {
                return ResourceManager.GetString("Hotels name or city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a few seconds!!!.
        /// </summary>
        public static string In_a_few_seconds___ {
            get {
                return ResourceManager.GetString("In a few seconds!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hotels name or city.
        /// </summary>
        public static string Input_hotels_name_or_city {
            get {
                return ResourceManager.GetString("Input hotels name or city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 1km.
        /// </summary>
        public static string Less_than_1km {
            get {
                return ResourceManager.GetString("Less than 1km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 3km.
        /// </summary>
        public static string Less_than_3km {
            get {
                return ResourceManager.GetString("Less than 3km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 5km.
        /// </summary>
        public static string Less_than_5km {
            get {
                return ResourceManager.GetString("Less than 5km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy statement.
        /// </summary>
        public static string Privacy_statement {
            get {
                return ResourceManager.GetString("Privacy statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register object.
        /// </summary>
        public static string Register_object {
            get {
                return ResourceManager.GetString("Register object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room facilities.
        /// </summary>
        public static string Room_facilities {
            get {
                return ResourceManager.GetString("Room facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send review about HotBooking.com.
        /// </summary>
        public static string Send_review_about_HotBooking_com {
            get {
                return ResourceManager.GetString("Send review about HotBooking.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service guarantee.
        /// </summary>
        public static string Service_guarantee {
            get {
                return ResourceManager.GetString("Service guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to star.
        /// </summary>
        public static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star rating.
        /// </summary>
        public static string Star_rating {
            get {
                return ResourceManager.GetString("Star rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stars.
        /// </summary>
        public static string stars {
            get {
                return ResourceManager.GetString("stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; conditions.
        /// </summary>
        public static string Terms___conditions {
            get {
                return ResourceManager.GetString("Terms & conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrated.
        /// </summary>
        public static string Unrated {
            get {
                return ResourceManager.GetString("Unrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website feedback.
        /// </summary>
        public static string Website_feedback {
            get {
                return ResourceManager.GetString("Website feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What people are saying.
        /// </summary>
        public static string What_people_are_saying {
            get {
                return ResourceManager.GetString("What people are saying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your budget (per night).
        /// </summary>
        public static string Your_budget__per_night_ {
            get {
                return ResourceManager.GetString("Your budget (per night)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your opinion.
        /// </summary>
        public static string Your_opinion {
            get {
                return ResourceManager.GetString("Your opinion", resourceCulture);
            }
        }
    }
}
